default_language_version:
  python: python3.11
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: identity
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args:
          [
            --py36-plus,
            --py37-plus,
            --py38-plus,
            --py39-plus,
            --py310-plus,
            --py311-plus,
          ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [--fix-only, --config=ruff.toml]
      - id: ruff-format
        args: [--config=ruff.toml]
  - repo: https://github.com/pdm-project/pdm
    rev: 2.12.3
    hooks:
      - id: pdm-lock-check
      - id: pdm-sync
      - id: pdm-export
        args: ["-o", "requirements.txt", "--without-hashes"]
        files: ^pdm.lock$
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
