default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
  - repo: https://github.com/pappasam/toml-sort.git
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/PyCQA/bandit.git
    rev: 1.7.5
    hooks:
      - id: bandit
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit.git
    rev: v0.0.287
    hooks:
      - id: ruff
        args: [--fix-only]
