[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "job-hunter"
version = "0.2.10-b6-dev13"
description = "Скрапер вакансий, который работает как с API, так и с обычными сайтами"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
asyncio = "*"
playwright = "*"
# uvloop = "*"
pandas = { version = ">=2.0", extras = ['pyarrow'] }
polars = { version = "^0.19.0", extras = ["pyarrow"] }
httpx = "^0.24.1"
attrs = "^23.1.0"
aioboto3 = { version = "^11.3.0", extras = ["boto3"] }
pre-commit = "^3.4.0"
more-itertools = "*"
yarl = "^1.9.2"
validators = "^0.22.0"
orjson = "^3.9.7"
regex = "^2023.8.8"
fake-useragent = "^1.2.1"
arrow = "^1.2.3"
pydantic-extra-types = "^2.1.0"
pydeps = "^1.12.17"
blinker = "^1.6.2"

[tool.poetry.group.dev]

[tool.poetry.group.dev.dependencies]
dynaconf = "*"
commitizen = "^3.10.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest-playwright = "*"
pytest = "*"
pytest-mock = "*"

[tool.pydeps]
max_bacon = 2
find_package = true
pylib = true
